### ISSUE TITLE
Adzan return nothing but arabic text

### ISSUE THREAD

**Issue by kfmd** [diorahman/adzan#2]
I'm not sure if this is still maintained but the command doesn't return adzan time, instead it return this:
`حي على الصلاة`

Where can I edit the script and change the city?

 I'm new but I'll try lol

**Comment by diorahman** [comment]
Well, yes it was a 5 minutes hack :smile: for an event. You can get the list of cities supported by the site by visiting and then open your browser dev tool and execute this:

```js
var a = document.querySelectorAll('select > option'); for (let i = 0; i < a.length; i++) console.log(a[i].value, a[i].innerText)
``` 
in the console. You will get something like:

![image](https://cloud.githubusercontent.com/assets/1234972/26566767/f41932a4-451f-11e7-9aee-beb775acac1c.png)

Then change the city value here: https://github.com/diorahman/adzan/blob/master/index.js#L7

Anyway, this is a very simple scrapping cli. If you want to extend it, that will be a great news :smile: 

BTW, I have fixed the issue, it turns out the request lib that we use hates redirection.

```
$ npm install -g adzan && adzan 
```
again and you will get the refreshed app.

**Comment by kfmd** [comment]
Thanks! I just started `coding` for fun, I'll tell you when I get there lol ^^

**Comment by kfmd** [comment]
Actually there is one more issue. 
I edited the city code in `usr/lib/node_modules/adzan/index.js`, but no matter what city code you put, the prayer time still shows prayer time for Jakarta

![screenshot from 2017-05-30 14-32-03](https://cloud.githubusercontent.com/assets/13399275/26572604/c7c0e5b0-4544-11e7-961f-8c96460edf78.png)

**Comment by diorahman** [comment]
Hi @alkaef please take a look at https://github.com/diorahman/adzan/issues/3 Seems for Yogyakarta it is `307` not `308`. However in the newer version of adzan (1.7.0) you can select city by telling adzan the index, e.g. for Yogyakarta

```
$ adzan 307
```

**Comment by kfmd** [comment]
Thank you so much @diorahman, this is so useful and simple!
